# name: "Build and Deploy"
# on:
#   push:
#     branches:
#       - main
#       - master
#     paths-ignore:
#       - .gitignore
#       - README.md
#       - LICENSE

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# # Allow one concurrent deployment
# concurrency:
#   group: "pages"
#   cancel-in-progress: true

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#           # submodules: true
#           # If using the 'assets' git submodule from Chirpy Starter, uncomment above
#           # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

#       - name: Setup Pages
#         id: pages
#         uses: actions/configure-pages@v3

#       - name: Setup Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 3   # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
#           bundler-cache: true

#       - name: Build site
#         run: bundle exec jekyll b -d "_site${{ steps.pages.outputs.base_path }}"
#         env:
#           JEKYLL_ENV: "production"

#       - name: Test site
#         run: |
#           bundle exec htmlproofer _site --disable-external --check-html --allow_hash_href

#       - name: Upload site artifact
#         uses: actions/upload-pages-artifact@v1
#         with:
#           path: "_site${{ steps.pages.outputs.base_path }}"

#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v1

name: "Build and Deploy"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04  # 关键修改：使用经过充分验证的旧版运行器
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true

      - name: Build site
        run: |
          mkdir -p "_site${{ steps.pages.outputs.base_path }}"
          bundle exec jekyll b -d "_site${{ steps.pages.outputs.base_path }}" --trace
        env:
          JEKYLL_ENV: "production"

      - name: Validate build
        run: |
          [ -d "_site${{ steps.pages.outputs.base_path }}" ] || (echo "Build failed"; exit 1)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # 升级到最新稳定版

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04  # 保持运行环境一致性
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3  # 使用最新部署组件